steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/smsai:$COMMIT_SHA', '.']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/smsai:$COMMIT_SHA']
  
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: 
      - 'run'
      - 'deploy'
      - 'smsai'
      - '--image'
      - 'gcr.io/$PROJECT_ID/smsai:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'TWILIO_ACCOUNT_SID=$$TWILIO_ACCOUNT_SID,TWILIO_AUTH_TOKEN=$$TWILIO_AUTH_TOKEN,TWILIO_PHONE_NUMBER=$$TWILIO_PHONE_NUMBER,CLAUDE_API_KEY=$$CLAUDE_API_KEY'
    secretEnv: ['TWILIO_ACCOUNT_SID', 'TWILIO_AUTH_TOKEN', 'TWILIO_PHONE_NUMBER', 'CLAUDE_API_KEY']

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/twilio-account-sid/versions/latest
    env: 'TWILIO_ACCOUNT_SID'
  - versionName: projects/$PROJECT_ID/secrets/twilio-auth-token/versions/latest
    env: 'TWILIO_AUTH_TOKEN'
  - versionName: projects/$PROJECT_ID/secrets/twilio-phone-number/versions/latest
    env: 'TWILIO_PHONE_NUMBER'
  - versionName: projects/$PROJECT_ID/secrets/claude-api-key/versions/latest
    env: 'CLAUDE_API_KEY'

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET